import Head from 'next/head';
import Image from 'next/image';
import { Spinner } from '@chakra-ui/react';
import { Canvas } from '@react-three/fiber';
import * as THREE from 'three';
import { useLoader } from '@react-three/fiber';
import {
	Environment,
	OrbitControls,
	Html,
	useProgress,
} from '@react-three/drei';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader';
import { MTLLoader } from 'three/examples/jsm/loaders/MTLLoader';
import { DDSLoader } from 'three-stdlib';
import { Suspense, useState } from 'react';
import { PugContainer, PugSpinner } from '../components/pug-loader';

function Scene() {
	const gltf = useLoader(GLTFLoader, '/pug_test-1.glb');
	console.log('ddd', gltf);
	return (
		<Suspense fallback={null}>
			<primitive object={gltf.scene} />
		</Suspense>
	);
}

// const Scene = () => {
// 	const materials = useLoader(MTLLoader, 'pug_pixel_0227-1.mtl');
// 	const obj = useLoader(OBJLoader, 'pug_pixel_0227-1.obj', (loader) => {
// 		materials.preload();
// 		loader.setMaterials(materials);
// 	});

// 	console.log(obj);
// 	return <primitive object={obj} scale={0.4} />;
// };

// function Loader() {
// 	const { progress } = useProgress();
// 	return <Html center>{progress} % loaded</Html>;
// }

export default function Home() {
	return (
		<div>
			<Head>
				<title>Abe Chen | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <h1>Hello World</h1> */}
			<PugContainer>
				<Canvas>
					<Suspense fallback={null}>
						<Scene />
						<spotLight position={[20, 10, 10]} angle={100} penumbra={3} />
						<ambientLight intensity={0.2} />
						<pointLight position={[-10, -10, -10]} />
						<OrbitControls />
					</Suspense>
				</Canvas>
			</PugContainer>
		</div>
	);
}
